# SPDX-FileCopyrightText: © 2026 Kevin Leon
name: Release
on:
  push:
    tags:
      - "v*"
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        sys:
          # - { os: windows, shell: 'msys2 {0}' }
          - { os: ubuntu,  shell: bash  }
          # exclude:  - { os: macos,   shell: bash  }
        wireshark:
          - 4.2.0
          - 4.4.0
          - 4.6.0

    runs-on: ${{ matrix.sys.os }}-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - name: Checkout Wireshark ${{ matrix.wireshark }}
      uses: actions/checkout@v4
      with:
        repository: wireshark/wireshark
        ref: v${{ matrix.wireshark }}
        path: wireshark
        fetch-depth: 0

    - name: Checkout GRCCSDS Plugin
      uses: actions/checkout@v4
      with:
        path: wireshark/plugins/epan/grccsds
        fetch-depth: 0

    - name: Install dependencies (Ubuntu)
      if: matrix.sys.os == 'ubuntu'
      run: sudo wireshark/tools/debian-setup.sh --install-all python3-pip -y

    - name: Install dependencies (Mac OS)
      if: matrix.sys.os == 'macos'
      run: |
        brew install lua@5.4
        version_greater_equal() { printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort; }
        SETUP_OPTIONS="--install-optional --install-doc-deps --install-dmg-deps --install-test-deps"
        if version_greater_equal ${{ matrix.wireshark }} 4.6; then
          SETUP_OPTIONS="${SETUP_OPTIONS} --install-required"
        fi
        wireshark/tools/macos-setup-brew.sh ${SETUP_OPTIONS}
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1

    - name: Install MSYS2 (Windows)
      if: matrix.sys.os == 'windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >- 
          base-devel
          msys2-keyring
          pacman
    - name: Fix MSYS2 PGP Keys (Windows)
      if: matrix.sys.os == 'windows'
      run: |
        pacman-key --init
        pacman-key --populate msys2
        pacman -Sy --noconfirm msys2-keyring
      shell: msys2 {0}

    - name: Install dependencies (Windows)
      if: matrix.sys.os == 'windows'
      run: wireshark/tools/msys2-setup.sh --install-all --noconfirm

    - name: Configure
      run: cmake -B build -S wireshark -G Ninja -DCUSTOM_PLUGIN_SRC_DIR=plugins/epan/grccsds -DCMAKE_INSTALL_PREFIX=/

    - name: Build
      run: |
        cmake --build build --target grccsds

    - name: Install
      env:
        DESTDIR: ${{ github.workspace }}/dist
      run: |
        cmake --build build --target plugins/epan/grccsds/install

    - name: Create ZIP archive (Windows)
      if: matrix.sys.os == 'windows'
      run: tar -czf GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.tar.gz -C dist .

    - name: Create ZIP archive (Linux/macOS)
      if: matrix.sys.os != 'windows'
      run: |
        zip -r GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.zip dist/
      shell: bash

    - name: Upload ZIP artifact (Windows)
      if: matrix.sys.os == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.tar.gz
        path: ./GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.tar.gz

    - name: Upload ZIP artifact (Linux/Macos)
      if: matrix.sys.os != 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.zip
        path: ./GRCCSDS_SPP_Wireshark_${{ matrix.wireshark }}_${{ matrix.sys.os }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all ZIP artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release_zips/

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./release_zips/*/*
        generateReleaseNotes: true
        draft: true
